name: flutter_application_1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

 
  go_router: ^14.2.0
  dio: ^5.5.0+1
  flutter_secure_storage: ^9.2.2
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  lottie: ^2.7.0
  google_fonts: ^6.1.0
  animate_do: ^3.0.2
  iconsax: ^0.0.8
  font_awesome_flutter: ^10.12.0
  flutter_staggered_grid_view: ^0.7.0
  confetti: ^0.8.0
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
